"""Description of changes

Revision ID: 61930c151ec3
Revises: 5f2ca50dd3ee
Create Date: 2023-11-08 18:28:10.843440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61930c151ec3'
down_revision = '5f2ca50dd3ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupation', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('occupation')

    # ### end Alembic commands ###
