"""Description of changes

Revision ID: ed8889cc9f52
Revises: 61930c151ec3
Create Date: 2023-11-08 18:33:38.096519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed8889cc9f52'
down_revision = '61930c151ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('age')
        batch_op.drop_column('occupation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupation', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
